config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts
  resources :pictures, only: [:create, :destroy]
  resources :tags, only: [:show]
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true
  has_ancestry
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :category

  validates :title, :summary, :body, presence: true

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page]) 
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, success: 'Категория успешно создана'
    else
      @categories = Category.all.order(:name)
      flash[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, success: 'Категория успешно обновлена'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      flash[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, success: 'Категория успешно удалена'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @abome = 'Святослав Мелихов'
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:medium), picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok} }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Статья успешно создана '
    else
      flash.now[:danger] = 'Статья не создана'
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, success: 'Статья успешно обновлена'
    else
      flash.now[:danger] = 'Статья не обновлена'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Статья успешно удалена'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, :all_tags, :summary, :category_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_breadcrumb(category)
    result = []
    category.ancestors.each do |ancestor|
      result << content_tag(:li, class: "breadcrumb-item") do
        link_to(ancestor.name, ancestor)
      end
    end
    result << content_tag(:li, category.name, class: "breadcrumb-item active")
    result.join('').html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @category do |f| %>
  <div class="form-group">
    <%=f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @category.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
    <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<div class="buttons_panel">
  <%= link_to 'Новая категория', new_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Название</th>
        <th>Категория родитель</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= category.name %></td>
          <td><%= category.parent.name if category.parent.present? %></td>
          <td>
            <%= link_to 'Изменить', edit_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
            <%= link_to 'Удалить', category_path(category), method: :delete, data: {confirm: 'Вы уверены?'}, class: 'btn btn-outline-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/categories/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form'  %>

app/views/categories/show.html.erb
<%= render 'shared/breadcrumb', category: @category %>

<h1><%= @category.name %></h1>

<section id="posts">
  <%= render @posts %>
</section>

<%= will_paginate @posts, rendered: 'BootstrapPaginationHelper::LinkRendered'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnBlock</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- <link rel="stylesheet" type="text/css" href="/home/svyat-mlhv/project/ruby/LRNBLCK/app/assets/stylesheets/main.sass"> -->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" >
        <div class="container-fluid">
          <!-- <a class="navbar-brand" href="<%= root_path %>">Курсовая работа по дисциплине "Системное администрирование" Мелихов С.А. | ИЦТМС 3-3 | НИУ МГСУ 2021</a> -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
                <a class="nav-link" href="<%= root_path %>">Курсовая работа по дисциплине "Системное администрирование"</a>
              <!-- </li>
              <% Category.order(:name).roots.each do |category| %>
                <li class="nav_item" <%= 'active' if current_page?(category_path(category))%>>
                  <%= link_to category.name, category, class: 'nav-link '%>
                </li>
              <% end %> -->
            </ul>
          </div>
        </div>
        <%# <%= link_to 'Новый раздел', new_post_path, class: 'btn btn-outline-primary pull-xs-right' %>
      </nav>
    </div>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
          <div class="alert alert-<%= name %>">
            <%= message %>
          </div>
          <% end %>
        </div>
      </div>

      <div class="row" >
        <div class="col-md-9">
          <%= yield %>
        </div>
        <div class="col-md-3 " >
          <div class="submenu sticky-top">
            <%= render 'shared/submenu' %>
          </div>

          <!-- <div class="tag_cloud ">
            <h2>Теги</h2>
            <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
            <% end %>
          </div> -->
        </div>
      </div>

    </div>

    <footer id="footer" class="footer navbar-fixed-bottom"><!--Footer-->
        <div class="footer-bottom">
            <div class="container">
                <div class="row  btn  ">
                    <p class="pull-left" style="background-color: #D3D3D3;">© 2021 | Luvest</p>
                    <p class="pull-right" >Мелихов Святослав | ИЦТМС 3-3 | НИУ МГСУ</p>
                </div>
            </div>
        </div>
    </footer><!--/Footer-->

  </body>
</html>

app/views/pages/about.html.erb
<h4> <%= @abome %> </h4>
<p>'aaaaaaaaa'</p>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { multipart: true} do |f| %>
  <div class="form-group">
    <%=f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%=f.label :summary %>
    <%= f.text_area :summary, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%=f.label :body %>
    <%= f.trix_editor :body, class: "editor" %>
  </div>

  <div class="form-group">
    <%=f.label :category_id %>
    <%=f.collection_select :category_id, Category.order(:name), :id, :name, {include_blank: true}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%=f.label :all_tags %>
    <%=f.text_field :all_tags, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
    <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <!-- <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time> -->
      <%# <% if post.category.present? %>
        <!-- | -->
        <%# <%= link_to post.category.name, post.category %>
      <%# <% end %>
      <%# | %>
      <%# <%= link_to 'Изменить', edit_post_path(post) %>
      <%# | %>
      <%# <%= link_to 'Удалить', post_path(post), method: :delete, data: {confirm: 'Вы уверены?'} %>
    </small>
  </section>

  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>

  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'tag tag-primary'}.join(' ')%>

  </section>
</article>

app/views/posts/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSCZ5qW41wtmD9HNw514U3NWEFbhjpYQFVXfQpCM3nagWnxBE2_8JDtxgHaznTgKyUSjFSVjLOJTLnu/embed?start=false&loop=true&delayms=3000" frameborder="0" width="780" height="467" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

<%= render @posts %>

app/views/posts/new.html.erb
<h2><%= t('posts.new.title') %></h2>

<%= render 'form'  %>

app/views/posts/show.html.erb
<%= render 'shared/breadcrumb', category: @post.category %>

<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <!-- <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time> -->
      <%# <% if @post.category.present? %>
        <%# | %>
        <%# <%= link_to @post.category.name, @post.category %>
      <%# <% end %>
      <%# | %>
      <%# <%= link_to 'Изменить', edit_post_path(@post) %>
      <%# | %>
      <%# <%= link_to 'Удалить', post_path(@post), method: :delete, data: {confirm: 'Вы уверены?'} %>
    </small>
  </section>

  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.body.html_safe %>
  </section>
</article>

app/views/shared/_breadcrumb.html.erb
<% if category.present? && category.parent %>
  <ol class="breadcrumb">
    <%= build_breadcrumb(category) %>
  </ol>
<% end %>

app/views/shared/_submenu.html.erb
<div class="submenu">
  <h2>Меню</h2>
  <ul class="nav nav-pills nav-stacked">
    <% Category.roots.each do |category| %>
      <li class='nav-item'>
        <%= link_to category.name, category, class: "nav-link #{'active' if current_page? (category_path(category)) || @post.present? && @post.category == category}" %>
        <%= render 'shared/submenu_categories', categories: category.root.descendants.arrange %>
      </li>
    <% end %>
  </ul>

</div>

app/views/shared/_submenu_categories.html.erb
<ul class="nav nav-pills nav-stacked nested_nav">
  <% categories.each do |category, children| %>
    <li>
      <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}" %>
      <%= render 'shared/submenu_categories', categories: children if children.present? %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.posts.empty? %>
    <h2>Статей нет</h2>
<% else %>
  <%= render @tag.posts%>
<% end %>